set(command "/opt/clion-2016.1.1/bin/cmake/bin/cmake;-P;/home/fabio/workspace/obj-viewer/libs/src/lodepng-master-stamp/download-lodepng-master.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/opt/clion-2016.1.1/bin/cmake/bin/cmake;-P;/home/fabio/workspace/obj-viewer/libs/src/lodepng-master-stamp/verify-lodepng-master.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
set(command "/opt/clion-2016.1.1/bin/cmake/bin/cmake;-P;/home/fabio/workspace/obj-viewer/libs/src/lodepng-master-stamp/extract-lodepng-master.cmake")

execute_process(COMMAND ${command} RESULT_VARIABLE result)
if(result)
  set(msg "Command failed (${result}):\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  message(FATAL_ERROR "${msg}")
endif()
